version: '3.8'

services:
  user-service:
    build:
      context: ./personal-stylist-backend/user-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - JWT_SECRET=personal_stylist_jwt_secret_key
      - JWT_EXPIRES_IN=7d
      - MONGODB_URI=mongodb://mongo:27017/personal-stylist
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    depends_on:
      - mongo
    networks:
      - stylist-network
    restart: unless-stopped

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - stylist-network
    restart: unless-stopped

networks:
  stylist-network:
    driver: bridge

volumes:
  mongo-data:
